create table players (
	id varchar(50) primary key,
	name varchar(100) not null,
	position varchar(10) not null,
	height int,
	weight int,
	url varchar(100) not null
);

create table season_totals (
	id int auto_increment primary key,
	player_id varchar(50) not null,
	season int not null,
	age int not null,
	team varchar(3) not null,
	league varchar(3) not null,
	position varchar(2) not null,
	games int not null,
	games_started int not null,
	minutes_played int not null,
	field_goals int not null,
	field_goal_attempts int not null,
	field_goal_pct float not null,
	three_point_field_goals int not null,
	three_point_field_goal_attempts int not null,
	three_point_field_goal_pct float not null,
	two_point_field_goals int not null,
	two_point_field_goal_attempts int not null,
	two_point_field_goal_pct float not null,
	free_throws int not null,
	free_throw_attempts int not null,
	free_throw_pct float not null,
	offensive_rebounds int not null,
	defensive_rebounds int not null,
	total_rebounds int not null,
	assists int not null,
	steals int not null,
	blocks int not null,
	turnovers int not null,
	personal_fouls int not null,
	points int not null,
	foreign key (player_id) references players(id)
);

create table season_advanced (
	id int auto_increment primary key,
	player_id varchar(50) not null,
	season int not null,
	age int not null,
	team varchar(3) not null,
	league varchar(3) not null,
	position varchar(2) not null,
	games int not null,
	minutes_played int not null,
	player_efficiency_rating float not null,
	true_shooting_pct float not null,
	effective_field_goal_pct float not null,
	free_throw_attempt_rate float not null,
	three_point_field_goal_attempt_rate float not null,
	offensive_rebound_pct float not null,
	defensive_rebound_pct float not null,
	total_rebound_pct float not null,
	assist_pct float not null,
	steal_pct float not null,
	block_pct float not null,
	turnover_pct float not null,
	usage_pct float not null,
	offensive_rating int not null,
	defensive_rating int not null,
	offensive_win_shares float not null,
	defensive_win_shares float not null,
	win_shares float not null,
	win_shares_per_48_minutes float not null,
	foreign key (player_id) references players(id)
);

create table game_totals_basic (
	id int auto_increment primary key,
	player_id varchar(50) not null,
	game_number int not null,
	date timestamp not null,
	age int not null,
	team varchar(3) not null,
	home boolean not null,
	opponent varchar(3) not null,
	result varchar(10) not null,
	games_started int not null,
	minutes_played float not null,
	field_goals int not null,
	field_goal_attempts int not null,
	field_goal_pct float not null,
	three_point_field_goals int not null,
	three_point_field_goal_attempts int not null,
	three_point_pct float not null,
	free_throws int not null,
	free_throw_attempts int not null,
	free_throw_pct float not null,
	offensive_rebounds int not null,
	defensive_rebounds int not null,
	total_rebounds int not null,
	assists int not null,
	steals int not null,
	blocks int not null,
	turnovers int not null,
	personal_fouls int not null,
	points int not null,
	game_score float not null,
	plus_minus int not null,
	foreign key (player_id) references players(id)
);

create table game_totals_advanced (
	id int auto_increment primary key,
	player_id varchar(50) not null,
	game_number int not null,
	date timestamp not null,
	age int not null,
	team varchar(3) not null,
	home boolean not null,
	opponent varchar(3) not null,
	result varchar(10) not null,
	games_started int not null,
	minutes_played float not null,
	true_shooting_pct float not null,
	effective_field_goal_pct float not null,
	offensive_rebound_pct float not null,
	defensive_rebound_pct float not null,
	total_rebound_pct float not null,
	assist_pct float not null,
	steal_pct float not null,
	block_pct float not null,
	turnover_pct float not null,
	usage_pct float not null,
	offensive_rating int not null,
	defensive_rating int not null,
	game_score float not null,
	foreign key (player_id) references players(id)
);

create table splits (
	id int auto_increment primary key,
	player_id varchar(50) not null,
	type varchar(50) not null,
	subtype varchar(50) not null,
	games int not null,
	games_started int not null,
	minutes_played int not null,
	field_goals int not null,
	field_goal_attempts int not null,
	three_point_field_goals int not null,
	three_point_field_goal_attempts int not null,
	free_throws int not null,
	free_throw_attempts int not null,
	offensive_rebounds int not null,
	defensive_rebounds int not null,
	total_rebounds int not null,
	assists int not null,
	steals int not null,
	blocks int not null,
	turnovers int not null,
	personal_fouls int not null,
	points int not null,
	field_goal_pct float not null,
	three_point_pct float not null,
	free_throw_pct float not null,
	true_shooting_pct float not null,
	offensive_rating int not null,
	defensive_rating int not null,
	plus_minus float not null,
	minutes_played_per_game float not null,
	points_per_game float not null,
	total_rebounds_per_game float not null,
	assists_per_game float not null,
	foreign key (player_id) references players(id)
);